app = "madsminder"             # <-- set to your Fly app name
primary_region = "mia"         # <-- set to the region where your volume lives

[env]
  DB_PATH = "/data/madsminder.db"
  TZ = "America/New_York"

[experimental]
  auto_stop_machines = false   # keep worker running (no autosuspend)
  auto_start_machines = true

[processes]
  app = "python bot.py"        # explicit long-running worker

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "256mb"

[[mounts]]
  source = "data"
  destination = "/data"
