name: Deploy to Fly (no Depot) 3
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  FLY_APP: madsminder          # <-- set to your app name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@v1

      - name: Flyctl auth docker
        run: flyctl auth docker
        env: { FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }} }

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & push image to Fly registry
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: registry.fly.io/${{ env.FLY_APP }}:${{ github.sha }}

      - name: Deploy image
        run: |
          flyctl deploy \
            --app "${{ env.FLY_APP }}" \
            --image "registry.fly.io/${{ env.FLY_APP }}:${{ github.sha }}" \
            --verbose
        env: { FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }} }

      - name: Status & recent logs (on failure)
        if: failure()
        run: |
          flyctl status --app "${{ env.FLY_APP }}" || true
          flyctl logs --app "${{ env.FLY_APP }}" --max-lines 200 || true
        env: { FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }} }
